---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trainings-configuration
  labels:
    app: fiufit
    tier: trainings-microservice
data:
  TRAININGS_DB_HOST: dpg-cikrbnlph6eg6ke1cgbg-a.oregon-postgres.render.com
  TRAININGS_DB_DATABASE: fiufit_4evp
  TRAININGS_DB_USER: "fiufit"
  TRAININGS_DB_PASSWORD: $USERS_DB_PASSWORD
  TRAININGS_DB_CREATE_STRUCTURES: "true"
  TRAININGS_AUTH_HOST: auth-service.taller2-marianocinalli.svc.cluster.local:8002
  TRAININGS_LOG_LEVEL: INFO
  TRAININGS_FIREBASE_PRIVATE_KEY: $TRAININGS_FIREBASE_PRIVATE_KEY
  NEW_RELIC_LICENSE_KEY: $TRAININGS_NEW_RELIC_KEY
  NEW_RELIC_APP_NAME: trainings
  NEW_RELIC_MONITOR_MODE: "true"
  NEW_RELIC_LOG: stderr
  NEW_RELIC_LOG_LEVEL: warning
