---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trainings-configuration
  labels:
    app: fiufit
    tier: trainings-microservice
data:
  TRAININGS_DB_DATABASE: "fiufit"
  TRAININGS_DB_USER: "backend"
  TRAININGS_DB_PASSWORD: $USERS_DB_PASSWORD
  TRAININGS_DB_HOST: "dpg-cgno8m8rddl9mmvdaja0-a.oregon-postgres.render.com"
