---
apiVersion: v1
kind: Service
metadata:
  name: trainings-service
  labels:
    app: fiufit
    tier: trainings-service
spec:
  type: ClusterIP
  ports:
  - name: trainings-svc
    protocol: TCP
    port: 8001
    targetPort: http-trainings
  selector:
    app: fiufit
    tier: trainings-microservice
